[extra_derives]
"*Error" = ["Serialize", "Deserialize"]
"User*" = ["Copy"]
"*" = ["PartialEq"]

[extra_use_statements]
"*Error" = ["serde::{Serialize, Deserialize}"]
"User*" = ["std::fmt"]
"*" = ["std::collections::HashMap"]