[[extra]]
matches = ".*Error$"
derive = ["Serialize", "Deserialize"]
use = ["serde::{Serialize, Deserialize}"]

[[extra]]
matches = "User.*"
derive = ["Copy"]
use = ["std::fmt"]

[[extra]]
matches = ".*"
derive = ["PartialEq"]
use = ["std::collections::HashMap"]